Extension { #name : #Object }

{ #category : #'*HaltManager' }
Object >> inactiveHalt [
]

{ #category : #'*HaltManager' }
Object >> inactiveHalt: anArgument [
]

{ #category : #'*HaltManager' }
Object >> inactiveHaltIf: anArgument [
]

{ #category : #'*HaltManager' }
Object >> inactiveHaltIfNil [
]

{ #category : #'*HaltManager' }
Object >> inactiveHaltOnCount: anArgument [
]

{ #category : #'*HaltManager' }
Object >> inactiveHaltOnce [
]
